/****************************************************************
   This file was created automatically by `FlexCat 1.5'
   from "AmiFTP.cd".

   Do NOT edit by hand!
****************************************************************/

#ifndef AmiFTP_CAT_H
#define AmiFTP_CAT_H


#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif	/*  !EXEC_TYPES_H	    */
#ifndef LIBRARIES_LOCALE_H
#include <libraries/locale.h>
#endif	/*  !LIBRARIES_LOCALE_H     */


/*  Prototypes	*/
extern void OpenAmiFTPCatalog(struct Locale *, STRPTR);
extern void CloseAmiFTPCatalog(void);
extern STRPTR GetAmiFTPString(APTR);

/*  Definitions */
extern const APTR _SLW_SiteListWindow;
#define SLW_SiteListWindow ((APTR) &_SLW_SiteListWindow)
extern const APTR _SLW_SiteList;
#define SLW_SiteList ((APTR) &_SLW_SiteList)
extern const APTR _SLW_Connect;
#define SLW_Connect ((APTR) &_SLW_Connect)
extern const APTR _SLW_New;
#define SLW_New ((APTR) &_SLW_New)
extern const APTR _SLW_Edit;
#define SLW_Edit ((APTR) &_SLW_Edit)
extern const APTR _SLW_Remove;
#define SLW_Remove ((APTR) &_SLW_Remove)
extern const APTR _SLW_Cancel;
#define SLW_Cancel ((APTR) &_SLW_Cancel)
extern const APTR _SLW_OK;
#define SLW_OK ((APTR) &_SLW_OK)
extern const APTR _SLW_Up;
#define SLW_Up ((APTR) &_SLW_Up)
extern const APTR _SLW_Down;
#define SLW_Down ((APTR) &_SLW_Down)
extern const APTR _SLW_Top;
#define SLW_Top ((APTR) &_SLW_Top)
extern const APTR _SLW_Bottom;
#define SLW_Bottom ((APTR) &_SLW_Bottom)
extern const APTR _SLW_Newstring;
#define SLW_Newstring ((APTR) &_SLW_Newstring)
extern const APTR _SLW_Sort;
#define SLW_Sort ((APTR) &_SLW_Sort)
extern const APTR _SCW_SiteConfigurationWindow;
#define SCW_SiteConfigurationWindow ((APTR) &_SCW_SiteConfigurationWindow)
extern const APTR _SCW_Name;
#define SCW_Name ((APTR) &_SCW_Name)
extern const APTR _SCW_Site;
#define SCW_Site ((APTR) &_SCW_Site)
extern const APTR _SCW_Port;
#define SCW_Port ((APTR) &_SCW_Port)
extern const APTR _SCW_RemDir;
#define SCW_RemDir ((APTR) &_SCW_RemDir)
extern const APTR _SCW_LocDir;
#define SCW_LocDir ((APTR) &_SCW_LocDir)
extern const APTR _SCW_Anonymous;
#define SCW_Anonymous ((APTR) &_SCW_Anonymous)
extern const APTR _SCW_LoginName;
#define SCW_LoginName ((APTR) &_SCW_LoginName)
extern const APTR _SCW_Password;
#define SCW_Password ((APTR) &_SCW_Password)
extern const APTR _SCW_OK;
#define SCW_OK ((APTR) &_SCW_OK)
extern const APTR _SCW_Cancel;
#define SCW_Cancel ((APTR) &_SCW_Cancel)
extern const APTR _SCW_OS;
#define SCW_OS ((APTR) &_SCW_OS)
extern const APTR _SCW_Proxy;
#define SCW_Proxy ((APTR) &_SCW_Proxy)
extern const APTR _SCW_HotList;
#define SCW_HotList ((APTR) &_SCW_HotList)
extern const APTR _TW_WinTitle;
#define TW_WinTitle ((APTR) &_TW_WinTitle)
extern const APTR _TW_RemoteFile;
#define TW_RemoteFile ((APTR) &_TW_RemoteFile)
extern const APTR _TW_LocalFile;
#define TW_LocalFile ((APTR) &_TW_LocalFile)
extern const APTR _TW_Size;
#define TW_Size ((APTR) &_TW_Size)
extern const APTR _TW_Cps;
#define TW_Cps ((APTR) &_TW_Cps)
extern const APTR _TW_DataTransferred;
#define TW_DataTransferred ((APTR) &_TW_DataTransferred)
extern const APTR _TW_Abort;
#define TW_Abort ((APTR) &_TW_Abort)
extern const APTR _TW_FileExists;
#define TW_FileExists ((APTR) &_TW_FileExists)
extern const APTR _TW_Overwrite;
#define TW_Overwrite ((APTR) &_TW_Overwrite)
extern const APTR _TW_Resume;
#define TW_Resume ((APTR) &_TW_Resume)
extern const APTR _TW_CancelTransfer;
#define TW_CancelTransfer ((APTR) &_TW_CancelTransfer)
extern const APTR _TW_DownloadDir;
#define TW_DownloadDir ((APTR) &_TW_DownloadDir)
extern const APTR _TW_GetDir;
#define TW_GetDir ((APTR) &_TW_GetDir)
extern const APTR _MPW_WinTitle;
#define MPW_WinTitle ((APTR) &_MPW_WinTitle)
extern const APTR _MPW_Password;
#define MPW_Password ((APTR) &_MPW_Password)
extern const APTR _MPW_ViewCommand;
#define MPW_ViewCommand ((APTR) &_MPW_ViewCommand)
extern const APTR _MPW_ProxyHost;
#define MPW_ProxyHost ((APTR) &_MPW_ProxyHost)
extern const APTR _MPW_ProxyPort;
#define MPW_ProxyPort ((APTR) &_MPW_ProxyPort)
extern const APTR _MPW_ProxyDefault;
#define MPW_ProxyDefault ((APTR) &_MPW_ProxyDefault)
extern const APTR _MPW_DefDownloadDir;
#define MPW_DefDownloadDir ((APTR) &_MPW_DefDownloadDir)
extern const APTR _MPW_IgnoreCase;
#define MPW_IgnoreCase ((APTR) &_MPW_IgnoreCase)
extern const APTR _MW_SiteName;
#define MW_SiteName ((APTR) &_MW_SiteName)
extern const APTR _MW_DirName;
#define MW_DirName ((APTR) &_MW_DirName)
extern const APTR _MW_DownloadDir;
#define MW_DownloadDir ((APTR) &_MW_DownloadDir)
extern const APTR _MW_Parent;
#define MW_Parent ((APTR) &_MW_Parent)
extern const APTR _MW_Get;
#define MW_Get ((APTR) &_MW_Get)
extern const APTR _MW_Put;
#define MW_Put ((APTR) &_MW_Put)
extern const APTR _MW_View;
#define MW_View ((APTR) &_MW_View)
extern const APTR _MW_Connect;
#define MW_Connect ((APTR) &_MW_Connect)
extern const APTR _MW_Disconnect;
#define MW_Disconnect ((APTR) &_MW_Disconnect)
extern const APTR _MW_DeleteRequest;
#define MW_DeleteRequest ((APTR) &_MW_DeleteRequest)
extern const APTR _MW_DeleteCancel;
#define MW_DeleteCancel ((APTR) &_MW_DeleteCancel)
extern const APTR _MW_Reload;
#define MW_Reload ((APTR) &_MW_Reload)
extern const APTR _CW_WinTitle;
#define CW_WinTitle ((APTR) &_CW_WinTitle)
extern const APTR _CW_Abort;
#define CW_Abort ((APTR) &_CW_Abort)
extern const APTR _CW_Site;
#define CW_Site ((APTR) &_CW_Site)
extern const APTR _CW_Status;
#define CW_Status ((APTR) &_CW_Status)
extern const APTR _CW_Connecting;
#define CW_Connecting ((APTR) &_CW_Connecting)
extern const APTR _CW_ReadingDir;
#define CW_ReadingDir ((APTR) &_CW_ReadingDir)
extern const APTR _CW_SendingLogin;
#define CW_SendingLogin ((APTR) &_CW_SendingLogin)
extern const APTR _CW_SendingPassword;
#define CW_SendingPassword ((APTR) &_CW_SendingPassword)
extern const APTR _CW_ChangingDirectory;
#define CW_ChangingDirectory ((APTR) &_CW_ChangingDirectory)
extern const APTR _MENU_Project;
#define MENU_Project ((APTR) &_MENU_Project)
extern const APTR _MENU_AddToSiteList;
#define MENU_AddToSiteList ((APTR) &_MENU_AddToSiteList)
extern const APTR _MENU_Reconnect;
#define MENU_Reconnect ((APTR) &_MENU_Reconnect)
extern const APTR _MENU_Iconify;
#define MENU_Iconify ((APTR) &_MENU_Iconify)
extern const APTR _MENU_About;
#define MENU_About ((APTR) &_MENU_About)
extern const APTR _MENU_Quit;
#define MENU_Quit ((APTR) &_MENU_Quit)
extern const APTR _MENU_Files;
#define MENU_Files ((APTR) &_MENU_Files)
extern const APTR _MENU_TagAll;
#define MENU_TagAll ((APTR) &_MENU_TagAll)
extern const APTR _MENU_UntagAll;
#define MENU_UntagAll ((APTR) &_MENU_UntagAll)
extern const APTR _MENU_TransferMode;
#define MENU_TransferMode ((APTR) &_MENU_TransferMode)
extern const APTR _MENU_Binary;
#define MENU_Binary ((APTR) &_MENU_Binary)
extern const APTR _MENU_ASCII;
#define MENU_ASCII ((APTR) &_MENU_ASCII)
extern const APTR _MENU_ClearCache;
#define MENU_ClearCache ((APTR) &_MENU_ClearCache)
extern const APTR _MENU_Delete;
#define MENU_Delete ((APTR) &_MENU_Delete)
extern const APTR _MENU_Move;
#define MENU_Move ((APTR) &_MENU_Move)
extern const APTR _MENU_Sort;
#define MENU_Sort ((APTR) &_MENU_Sort)
extern const APTR _MENU_SortbyName;
#define MENU_SortbyName ((APTR) &_MENU_SortbyName)
extern const APTR _MENU_SortbyDate;
#define MENU_SortbyDate ((APTR) &_MENU_SortbyDate)
extern const APTR _MENU_Settings;
#define MENU_Settings ((APTR) &_MENU_Settings)
extern const APTR _MENU_Global;
#define MENU_Global ((APTR) &_MENU_Global)
extern const APTR _MENU_Hostlist;
#define MENU_Hostlist ((APTR) &_MENU_Hostlist)
extern const APTR _MENU_LogWindow;
#define MENU_LogWindow ((APTR) &_MENU_LogWindow)
extern const APTR _MENU_ToggleDotFiles;
#define MENU_ToggleDotFiles ((APTR) &_MENU_ToggleDotFiles)
extern const APTR _MENU_LoadSettings;
#define MENU_LoadSettings ((APTR) &_MENU_LoadSettings)
extern const APTR _MENU_SaveSettings;
#define MENU_SaveSettings ((APTR) &_MENU_SaveSettings)
extern const APTR _MENU_SaveSettingsAs;
#define MENU_SaveSettingsAs ((APTR) &_MENU_SaveSettingsAs)
extern const APTR _MENU_HotList;
#define MENU_HotList ((APTR) &_MENU_HotList)
extern const APTR _Str_ErrorReadingDir;
#define Str_ErrorReadingDir ((APTR) &_Str_ErrorReadingDir)
extern const APTR _Str_CannotDLDirs;
#define Str_CannotDLDirs ((APTR) &_Str_CannotDLDirs)
extern const APTR _Str_SelectDLPath;
#define Str_SelectDLPath ((APTR) &_Str_SelectDLPath)
extern const APTR _Str_SelectULFiles;
#define Str_SelectULFiles ((APTR) &_Str_SelectULFiles)
extern const APTR _Str_CDFailedTimedout;
#define Str_CDFailedTimedout ((APTR) &_Str_CDFailedTimedout)
extern const APTR _Str_CDFailed;
#define Str_CDFailed ((APTR) &_Str_CDFailed)
extern const APTR _Str_AmiFTPError;
#define Str_AmiFTPError ((APTR) &_Str_AmiFTPError)
extern const APTR _Str_OK;
#define Str_OK ((APTR) &_Str_OK)
extern const APTR _Str_CANCEL;
#define Str_CANCEL ((APTR) &_Str_CANCEL)
extern const APTR _Str_PasswordRequest;
#define Str_PasswordRequest ((APTR) &_Str_PasswordRequest)
extern const APTR _Str_PasswordEntry;
#define Str_PasswordEntry ((APTR) &_Str_PasswordEntry)
extern const APTR _Str_ServiceNotAvail;
#define Str_ServiceNotAvail ((APTR) &_Str_ServiceNotAvail)
extern const APTR _Str_ConnectFailed;
#define Str_ConnectFailed ((APTR) &_Str_ConnectFailed)
extern const APTR _Str_ConnectLoginFailed;
#define Str_ConnectLoginFailed ((APTR) &_Str_ConnectLoginFailed)
extern const APTR _Str_Putfailed;
#define Str_Putfailed ((APTR) &_Str_Putfailed)
extern const APTR _Str_RemoteWriteFailed;
#define Str_RemoteWriteFailed ((APTR) &_Str_RemoteWriteFailed)
extern const APTR _Str_GetFailed;
#define Str_GetFailed ((APTR) &_Str_GetFailed)
extern const APTR _Str_LocalfileError;
#define Str_LocalfileError ((APTR) &_Str_LocalfileError)
extern const APTR _Str_LocalWriteFailed;
#define Str_LocalWriteFailed ((APTR) &_Str_LocalWriteFailed)
extern const APTR _Str_NoSuchDir;
#define Str_NoSuchDir ((APTR) &_Str_NoSuchDir)
extern const APTR _Str_DisconnectedTimeout;
#define Str_DisconnectedTimeout ((APTR) &_Str_DisconnectedTimeout)
extern const APTR _Str_Outofmem;
#define Str_Outofmem ((APTR) &_Str_Outofmem)
extern const APTR _Str_SelectSettingsFile;
#define Str_SelectSettingsFile ((APTR) &_Str_SelectSettingsFile)
extern const APTR _Str_NoRestart;
#define Str_NoRestart ((APTR) &_Str_NoRestart)
extern const APTR _Str_ConnectionTimedOut;
#define Str_ConnectionTimedOut ((APTR) &_Str_ConnectionTimedOut)
extern const APTR _Str_AmiFTPRequest;
#define Str_AmiFTPRequest ((APTR) &_Str_AmiFTPRequest)
extern const APTR _Str_AboutAmiFTP;
#define Str_AboutAmiFTP ((APTR) &_Str_AboutAmiFTP)
extern const APTR _Str_UnknownHost;
#define Str_UnknownHost ((APTR) &_Str_UnknownHost)
extern const APTR _Str_ErrorBuildingDirList;
#define Str_ErrorBuildingDirList ((APTR) &_Str_ErrorBuildingDirList)
extern const APTR _Str_Translator;
#define Str_Translator ((APTR) &_Str_Translator)
extern const APTR _SLW_NewGroup;
#define SLW_NewGroup ((APTR) &_SLW_NewGroup)
extern const APTR _SLW_AddBar;
#define SLW_AddBar ((APTR) &_SLW_AddBar)
extern const APTR _MENU_ToggleADTFiles;
#define MENU_ToggleADTFiles ((APTR) &_MENU_ToggleADTFiles)
extern const APTR _MENU_ResetADT;
#define MENU_ResetADT ((APTR) &_MENU_ResetADT)
extern const APTR _MW_ViewReadme;
#define MW_ViewReadme ((APTR) &_MW_ViewReadme)
extern const APTR _MPW_General;
#define MPW_General ((APTR) &_MPW_General)
extern const APTR _MPW_ADT;
#define MPW_ADT ((APTR) &_MPW_ADT)
extern const APTR _MPW_Proxy;
#define MPW_Proxy ((APTR) &_MPW_Proxy)
extern const APTR _MPW_BufferSize;
#define MPW_BufferSize ((APTR) &_MPW_BufferSize)
extern const APTR _MPW_DirCacheSize;
#define MPW_DirCacheSize ((APTR) &_MPW_DirCacheSize)
extern const APTR _MPW_DeleteViewed;
#define MPW_DeleteViewed ((APTR) &_MPW_DeleteViewed)
extern const APTR _MPW_Beep;
#define MPW_Beep ((APTR) &_MPW_Beep)
extern const APTR _MPW_HideDirectories;
#define MPW_HideDirectories ((APTR) &_MPW_HideDirectories)
extern const APTR _MPW_PreservePath;
#define MPW_PreservePath ((APTR) &_MPW_PreservePath)
extern const APTR _MPW_ShowMOTD;
#define MPW_ShowMOTD ((APTR) &_MPW_ShowMOTD)
extern const APTR _MPW_GetReadme;
#define MPW_GetReadme ((APTR) &_MPW_GetReadme)
extern const APTR _SCW_AminetMode;
#define SCW_AminetMode ((APTR) &_SCW_AminetMode)
extern const APTR _MPW_OK;
#define MPW_OK ((APTR) &_MPW_OK)
extern const APTR _MPW_Cancel;
#define MPW_Cancel ((APTR) &_MPW_Cancel)
extern const APTR _TW_TimeLeft;
#define TW_TimeLeft ((APTR) &_TW_TimeLeft)
extern const APTR _Str_NoNewAminetFiles;
#define Str_NoNewAminetFiles ((APTR) &_Str_NoNewAminetFiles)
extern const APTR _Str_WindowTitle;
#define Str_WindowTitle ((APTR) &_Str_WindowTitle)
extern const APTR _MENU_Connect;
#define MENU_Connect ((APTR) &_MENU_Connect)
extern const APTR _MENU_Disconnect;
#define MENU_Disconnect ((APTR) &_MENU_Disconnect)
extern const APTR _MENU_Get;
#define MENU_Get ((APTR) &_MENU_Get)
extern const APTR _MENU_Put;
#define MENU_Put ((APTR) &_MENU_Put)
extern const APTR _MENU_View;
#define MENU_View ((APTR) &_MENU_View)
extern const APTR _MENU_PatternSelect;
#define MENU_PatternSelect ((APTR) &_MENU_PatternSelect)
extern const APTR _MPW_Display;
#define MPW_Display ((APTR) &_MPW_Display)
extern const APTR _Str_PatternRequest;
#define Str_PatternRequest ((APTR) &_Str_PatternRequest)
extern const APTR _Str_SelectPattern;
#define Str_SelectPattern ((APTR) &_Str_SelectPattern)
extern const APTR _MENU_Parent;
#define MENU_Parent ((APTR) &_MENU_Parent)
extern const APTR _MPW_PublicScreen;
#define MPW_PublicScreen ((APTR) &_MPW_PublicScreen)
extern const APTR _MPW_SystemFonts;
#define MPW_SystemFonts ((APTR) &_MPW_SystemFonts)
extern const APTR _MPW_InterfaceFont;
#define MPW_InterfaceFont ((APTR) &_MPW_InterfaceFont)
extern const APTR _MPW_FilelistFont;
#define MPW_FilelistFont ((APTR) &_MPW_FilelistFont)
extern const APTR _MPW_ShowButtons;
#define MPW_ShowButtons ((APTR) &_MPW_ShowButtons)
extern const APTR _MPW_ShowToolbar;
#define MPW_ShowToolbar ((APTR) &_MPW_ShowToolbar)
extern const APTR _MENU_ViewReadme;
#define MENU_ViewReadme ((APTR) &_MENU_ViewReadme)
extern const APTR _MPW_DefaultScreen;
#define MPW_DefaultScreen ((APTR) &_MPW_DefaultScreen)
extern const APTR _TW_OverwriteAll;
#define TW_OverwriteAll ((APTR) &_TW_OverwriteAll)
extern const APTR _MENU_CreateDir;
#define MENU_CreateDir ((APTR) &_MENU_CreateDir)
extern const APTR _Str_RemoteDir;
#define Str_RemoteDir ((APTR) &_Str_RemoteDir)
extern const APTR _MENU_RawCommand;
#define MENU_RawCommand ((APTR) &_MENU_RawCommand)
extern const APTR _MENU_Rename;
#define MENU_Rename ((APTR) &_MENU_Rename)
extern const APTR _MPW_ShowToolbar_NO;
#define MPW_ShowToolbar_NO ((APTR) &_MPW_ShowToolbar_NO)
extern const APTR _MPW_ShowToolbar_BOTH;
#define MPW_ShowToolbar_BOTH ((APTR) &_MPW_ShowToolbar_BOTH)
extern const APTR _MPW_ShowToolbar_TEXT;
#define MPW_ShowToolbar_TEXT ((APTR) &_MPW_ShowToolbar_TEXT)
extern const APTR _MPW_ShowToolbar_IMAGES;
#define MPW_ShowToolbar_IMAGES ((APTR) &_MPW_ShowToolbar_IMAGES)


#endif /*   !AmiFTP_CAT_H  */
