#ifndef MENUCLASS_H
#define MENUCLASS_H


enum {
    MNU_ProjectTitle=0,
    MNU_Connect,
    MNU_Disconnect,
    MNU_Reconnect,
    MNU_RawCommand,
    MNU_AddToSiteList,
    MNU_BarLabel1,
    MNU_ResetADT,
    MNU_BarLabel2,
    MNU_Iconify,
    MNU_BarLabel3,
    MNU_About,
    MNU_BarLabel4,
    MNU_Quit,
    MNU_FilesTitle,
    MNU_SelectAll,
    MNU_UnselectAll,
    MNU_PatternSelect,
    MNU_BarLabel5,
    MNU_TransferMode,
    MNU_BinaryTransferMode,
    MNU_AsciiTransferMode,
    MNU_BarLabel6,
    MNU_ClearCache,
    MNU_BarLabel7,
    MNU_Parent,
    MNU_Get,
    MNU_Put,
    MNU_View,
    MNU_ViewReadme,
    MNU_CreateDir,
    MNU_Delete,
    MNU_Rename,
    MNU_SortTitle,
    MNU_SortByName,
    MNU_SortByDate,
    MNU_SettingsTitle,
    MNU_OpenPrefsWindow,
    MNU_HostlistPrefs,
    MNU_BarLabel8,
    MNU_LogWindow,
    MNU_ToggleDotFiles,
    MNU_ToggleADT,
    MNU_BarLabel9,
    MNU_LoadPrefs,
    MNU_SavePrefs,
    MNU_SavePrefsAs,
    MNU_HotListTitle,
};


#endif
